FROM node:17.0.0 AS dev

RUN apt-get update

WORKDIR /usr/src/app

COPY . ./

# ENV PATH /app/node_modules/.bin:$PATH

# COPY package.json ./

# COPY package-lock.json ./

# RUN npm install --silent

# RUN npm install react-scripts@3.4.1 -g --silent
